# Generated by Django 5.0.7 on 2024-07-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='tile',
            new_name='title',
        ),
    ]
