# Generated by Django 5.0.7 on 2024-07-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_tile_todolist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='task_type',
        ),
        migrations.DeleteModel(
            name='ToDoType',
        ),
    ]
